#!/usr/bin/with-contenv sh
# exec s6-setuidgid mysql /usr/bin/mysqld --user=mysql --console --skip-name-resolve --skip-networking=0 $@
exec s6-setuidgid mysql /usr/bin/mysqld --user=mysql --console --skip-name-resolve --skip-networking=0
